name: Build React Native Android App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Android
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repo
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Setup Node.js environment
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install

    # Step 4: Setup JDK
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 11

    # Step 5: Setup Android SDK
    - name: Setup Android SDK
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 31
        target: default
        arch: x86_64
        profile: Nexus_5x
        script: echo "Android SDK setup completed"


    # Step 6: Build APK
    - name: Build APK
      run: |
        cd android
        ./gradlew assembleRelease
      env:
        JAVA_HOME: ${{ env.JAVA_HOME }}
        ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}

    # Step 7: Upload APK
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release.apk
        path: android/app/build/outputs/apk/release/app-release.apk
